name: Test

on:
  
  push:
    tags-ignore: [ '**' ]
    branches-ignore: [ master ]
    
jobs:
      
  test:
    strategy:
      matrix:
        go-version: [1.13, 1.14]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Test
      run: go test ./...

    - name: Race
      run: go test -race
